services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq-host
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ messaging port
      - "127.0.0.1:15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
