# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cricket.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cricket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcricket.proto\x12\x02pb\"\x1d\n\rPlayerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"0\n\x12UpdateScoreRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04runs\x18\x02 \x01(\r\"A\n\rStatsResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61verage\x18\x02 \x01(\x01\x12\x11\n\tcenturies\x18\x03 \x01(\r\"1\n\x10TopScoreResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61verage\x18\x02 \x01(\x01\"5\n\x12\x43\x65nturionsResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tcenturies\x18\x02 \x01(\r\"\x07\n\x05\x45mpty2\xdf\x01\n\x07\x43ricket\x12\x30\n\rgetTopScorers\x12\t.pb.Empty\x1a\x14.pb.TopScoreResponse\x12\x32\n\rgetCenturions\x12\t.pb.Empty\x1a\x16.pb.CenturionsResponse\x12\x36\n\x0egetPlayerStats\x12\x11.pb.PlayerRequest\x1a\x11.pb.StatsResponse\x12\x36\n\x11updatePlayerScore\x12\x16.pb.UpdateScoreRequest\x1a\t.pb.EmptyB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cricket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_PLAYERREQUEST']._serialized_start=21
  _globals['_PLAYERREQUEST']._serialized_end=50
  _globals['_UPDATESCOREREQUEST']._serialized_start=52
  _globals['_UPDATESCOREREQUEST']._serialized_end=100
  _globals['_STATSRESPONSE']._serialized_start=102
  _globals['_STATSRESPONSE']._serialized_end=167
  _globals['_TOPSCORERESPONSE']._serialized_start=169
  _globals['_TOPSCORERESPONSE']._serialized_end=218
  _globals['_CENTURIONSRESPONSE']._serialized_start=220
  _globals['_CENTURIONSRESPONSE']._serialized_end=273
  _globals['_EMPTY']._serialized_start=275
  _globals['_EMPTY']._serialized_end=282
  _globals['_CRICKET']._serialized_start=285
  _globals['_CRICKET']._serialized_end=508
# @@protoc_insertion_point(module_scope)
