# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cricket_pb2 as cricket__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cricket_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CricketStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTopScorers = channel.unary_unary(
                '/pb.Cricket/getTopScorers',
                request_serializer=cricket__pb2.Empty.SerializeToString,
                response_deserializer=cricket__pb2.TopScoreResponse.FromString,
                _registered_method=True)
        self.getCenturions = channel.unary_unary(
                '/pb.Cricket/getCenturions',
                request_serializer=cricket__pb2.Empty.SerializeToString,
                response_deserializer=cricket__pb2.CenturionsResponse.FromString,
                _registered_method=True)
        self.getPlayerStats = channel.unary_unary(
                '/pb.Cricket/getPlayerStats',
                request_serializer=cricket__pb2.PlayerRequest.SerializeToString,
                response_deserializer=cricket__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.updatePlayerScore = channel.unary_unary(
                '/pb.Cricket/updatePlayerScore',
                request_serializer=cricket__pb2.UpdateScoreRequest.SerializeToString,
                response_deserializer=cricket__pb2.Empty.FromString,
                _registered_method=True)


class CricketServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getTopScorers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCenturions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPlayerStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updatePlayerScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CricketServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTopScorers': grpc.unary_unary_rpc_method_handler(
                    servicer.getTopScorers,
                    request_deserializer=cricket__pb2.Empty.FromString,
                    response_serializer=cricket__pb2.TopScoreResponse.SerializeToString,
            ),
            'getCenturions': grpc.unary_unary_rpc_method_handler(
                    servicer.getCenturions,
                    request_deserializer=cricket__pb2.Empty.FromString,
                    response_serializer=cricket__pb2.CenturionsResponse.SerializeToString,
            ),
            'getPlayerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.getPlayerStats,
                    request_deserializer=cricket__pb2.PlayerRequest.FromString,
                    response_serializer=cricket__pb2.StatsResponse.SerializeToString,
            ),
            'updatePlayerScore': grpc.unary_unary_rpc_method_handler(
                    servicer.updatePlayerScore,
                    request_deserializer=cricket__pb2.UpdateScoreRequest.FromString,
                    response_serializer=cricket__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Cricket', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.Cricket', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cricket(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getTopScorers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Cricket/getTopScorers',
            cricket__pb2.Empty.SerializeToString,
            cricket__pb2.TopScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCenturions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Cricket/getCenturions',
            cricket__pb2.Empty.SerializeToString,
            cricket__pb2.CenturionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getPlayerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Cricket/getPlayerStats',
            cricket__pb2.PlayerRequest.SerializeToString,
            cricket__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updatePlayerScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Cricket/updatePlayerScore',
            cricket__pb2.UpdateScoreRequest.SerializeToString,
            cricket__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
